"""empty message

Revision ID: b80bf4b186b0
Revises: d185e098e1c1
Create Date: 2020-02-03 23:19:34.597386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80bf4b186b0'
down_revision = 'd185e098e1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawalrequests', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_withdrawalrequests_timestamp'), 'withdrawalrequests', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawalrequests_timestamp'), table_name='withdrawalrequests')
    op.drop_column('withdrawalrequests', 'timestamp')
    # ### end Alembic commands ###
