"""empty message

Revision ID: bfa89b010f66
Revises: 62604ec34f6d
Create Date: 2019-12-18 12:59:26.905028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa89b010f66'
down_revision = '62604ec34f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfers_timestamp', table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfers_timestamp', 'transfers', ['timestamp'], unique=False)
    # ### end Alembic commands ###
